### ISSUE TITLE
有问题，不知道为什么

### ISSUE THREAD

**Issue by 5rKB5bPlusD** [changzhiwin/yapi-plugin-import-rap2#1]
```json
{
    "code": -1,
    "msg": "服务器出错...",
    "error": {
        "message": "socket hang up",
        "name": "Error",
        "stack": "Error: socket hang up\n    at connResetException (internal/errors.js:607:14)\n    at Socket.socketOnEnd (_http_client.js:493:23)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
        "config": {
            "url": "http://xxxx/repository/get",
            "method": "get",
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "User-Agent": "axios/0.21.0"
            },
            "params": {
                "id": "31"
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1
        },
        "code": "ECONNRESET"
    }
}
```

**Comment by zzmg** [comment]
你访问一下这个试试  http://xxxx/repository/get
